# Generated by Django 5.2.8 on 2025-12-03 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_requisitionstatushistory_changed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('payment_terms', models.CharField(default='Net 30', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Supplier'), ('ordered', 'Ordered'), ('partially_received', 'Partially Received'), ('received', 'Fully Received'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(default='Net 30', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_pos', to='myapp.admin')),
            ],
            options={
                'db_table': 'purchase_order',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('old_status', models.CharField(blank=True, max_length=30, null=True)),
                ('new_status', models.CharField(max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.admin')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_order_history',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('po_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier_product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quality_status', models.CharField(choices=[('pending', 'Pending QC'), ('passed', 'Passed'), ('failed', 'Failed'), ('partial', 'Partially Passed')], default='pending', max_length=20)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
            ],
            options={
                'db_table': 'purchase_order_item',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiving',
            fields=[
                ('receiving_id', models.AutoField(primary_key=True, serialize=False)),
                ('receive_date', models.DateTimeField(auto_now_add=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_note_number', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier', models.CharField(blank=True, max_length=100, null=True)),
                ('quality_check_notes', models.TextField(blank=True, null=True)),
                ('overall_status', models.CharField(choices=[('pending', 'Pending QC'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('partial', 'Partially Accepted')], default='pending', max_length=20)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaseorder')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.admin')),
            ],
            options={
                'db_table': 'purchase_receiving',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('denied', 'Denied'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchases', to='myapp.admin')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='myapp.admin')),
                ('requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.requisition')),
            ],
            options={
                'db_table': 'purchase_request',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaserequest'),
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_to_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_estimated_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaserequest')),
                ('requisition_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.requisition_item')),
            ],
            options={
                'db_table': 'purchase_request_item',
            },
        ),
        migrations.CreateModel(
            name='ReceivedItem',
            fields=[
                ('received_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_accepted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_rejected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('quality_check_date', models.DateTimeField(blank=True, null=True)),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaseorderitem')),
                ('quality_checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.admin')),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchasereceiving')),
            ],
            options={
                'db_table': 'received_item',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierQuotation',
            fields=[
                ('quotation_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaseorderitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier')),
            ],
            options={
                'db_table': 'supplier_quotation',
            },
        ),
    ]
