# Generated by Django 5.2.8 on 2025-12-03 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_supplier_purchaseorder_purchaseorderhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_pos', to='myapp.admin'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='request',
            field=models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaserequest'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorderhistory',
            name='changed_by',
            field=models.ForeignKey(db_column='changed_by', on_delete=django.db.models.deletion.CASCADE, to='myapp.admin'),
        ),
        migrations.AlterField(
            model_name='purchaseorderhistory',
            name='po',
            field=models.ForeignKey(db_column='po_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='po',
            field=models.ForeignKey(db_column='po_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.products'),
        ),
        migrations.AlterField(
            model_name='purchasereceiving',
            name='po',
            field=models.ForeignKey(db_column='po_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchasereceiving',
            name='received_by',
            field=models.ForeignKey(db_column='received_by', on_delete=django.db.models.deletion.CASCADE, to='myapp.admin'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchases', to='myapp.admin'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='requested_by',
            field=models.ForeignKey(db_column='requested_by', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='myapp.admin'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='requisition',
            field=models.ForeignKey(blank=True, db_column='requisition_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.requisition'),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.products'),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='request',
            field=models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaserequest'),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='requisition_item',
            field=models.ForeignKey(blank=True, db_column='requisition_item_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.requisition_item'),
        ),
        migrations.AlterField(
            model_name='receiveditem',
            name='po_item',
            field=models.ForeignKey(db_column='po_item_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaseorderitem'),
        ),
        migrations.AlterField(
            model_name='receiveditem',
            name='quality_checker',
            field=models.ForeignKey(blank=True, db_column='quality_checker', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.admin'),
        ),
        migrations.AlterField(
            model_name='receiveditem',
            name='receiving',
            field=models.ForeignKey(db_column='receiving_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.purchasereceiving'),
        ),
        migrations.AlterField(
            model_name='supplierquotation',
            name='po_item',
            field=models.ForeignKey(db_column='po_item_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaseorderitem'),
        ),
        migrations.AlterField(
            model_name='supplierquotation',
            name='supplier',
            field=models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier'),
        ),
    ]
