# Generated by Django 5.2.8 on 2025-12-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_purchaseorder_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition_item',
            name='fulfilled_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
