# Generated by Django 5.2.8 on 2025-12-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_requisition_item_fulfilled_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('bank_transfer', 'Bank Transfer'), ('gcash', 'GCash'), ('check', 'Check'), ('credit', 'Credit')], default='cash_on_delivery', max_length=50),
        ),
    ]
