# Generated by Django 5.2.8 on 2025-12-05 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_purchaserequest_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='purpose',
            field=models.CharField(blank=True, default='Stock Issuance', max_length=255),
        ),
        migrations.AddField(
            model_name='stockout',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.requisition'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('issued', 'Issued'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='reserved', max_length=20),
        ),
    ]
