# Generated by Django 5.2.8 on 2025-12-07 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_admin_created_at_admin_is_active_admin_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='admin',
            field=models.ForeignKey(db_column='acc_id', on_delete=django.db.models.deletion.CASCADE, related_name='employee_record', to='myapp.admin'),
        ),
    ]
