# Generated by Django 5.2.8 on 2025-12-10 04:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_employee_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceiving',
            name='receiving_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='purchasereceiving',
            name='overall_status',
            field=models.CharField(choices=[('pending', 'Pending QC'), ('partial', 'Partially Received'), ('complete', 'Complete'), ('with_rejections', 'Complete with Rejections'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('check_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('overall_status', models.CharField(default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rejection_disposition', models.CharField(blank=True, choices=[('return', 'Return to Supplier'), ('keep_as_rejected', 'Keep as Rejected Stock'), ('destroy', 'Destroy/Dispose'), ('replace', 'Request Replacement')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checker', models.ForeignKey(db_column='checker', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.admin')),
                ('receiving', models.ForeignKey(db_column='receiving_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.purchasereceiving')),
            ],
            options={
                'db_table': 'quality_check',
            },
        ),
        migrations.CreateModel(
            name='RejectedItem',
            fields=[
                ('rejected_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('damaged', 'Damaged Goods'), ('wrong_item', 'Wrong Item'), ('expired', 'Expired Product'), ('poor_quality', 'Poor Quality'), ('shortage', 'Short Quantity'), ('wrong_spec', 'Wrong Specifications'), ('late_delivery', 'Late Delivery'), ('packaging_issue', 'Packaging Issue'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('disposition', models.CharField(max_length=20)),
                ('disposition_date', models.DateTimeField(blank=True, null=True)),
                ('disposition_notes', models.TextField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disposed_by', models.ForeignKey(blank=True, db_column='disposed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.admin')),
                ('po_item', models.ForeignKey(db_column='po_item_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaseorderitem')),
                ('receiving', models.ForeignKey(db_column='receiving_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.purchasereceiving')),
            ],
            options={
                'db_table': 'rejected_item',
            },
        ),
        migrations.CreateModel(
            name='DisposalRecord',
            fields=[
                ('disposal_id', models.AutoField(primary_key=True, serialize=False)),
                ('disposal_number', models.CharField(max_length=50, unique=True)),
                ('method', models.CharField(choices=[('landfill', 'Landfill'), ('incineration', 'Incineration'), ('recycling', 'Recycling'), ('donation', 'Donation'), ('other', 'Other')], max_length=20)),
                ('disposal_date', models.DateField()),
                ('witness', models.CharField(blank=True, max_length=200, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disposed_by', models.ForeignKey(db_column='disposed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.admin')),
                ('rejected_item', models.ForeignKey(db_column='rejected_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.rejecteditem')),
            ],
            options={
                'db_table': 'disposal_record',
            },
        ),
        migrations.CreateModel(
            name='RejectedStock',
            fields=[
                ('rejected_stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('quarantine', 'In Quarantine'), ('rework', 'Awaiting Rework'), ('scrap', 'For Scrap'), ('return_pending', 'Pending Return'), ('returned', 'Returned'), ('destroyed', 'Destroyed'), ('replaced', 'Replaced')], default='quarantine', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
                ('rejected_item', models.ForeignKey(db_column='rejected_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.rejecteditem')),
            ],
            options={
                'db_table': 'rejected_stock',
            },
        ),
        migrations.CreateModel(
            name='ReplacementRequest',
            fields=[
                ('replacement_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_number', models.CharField(max_length=50, unique=True)),
                ('requested_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('ordered', 'Ordered'), ('shipped', 'Shipped'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rejected_item', models.ForeignKey(db_column='rejected_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.rejecteditem')),
                ('replacement_po', models.ForeignKey(blank=True, db_column='replacement_po_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.purchaseorder')),
                ('requested_by', models.ForeignKey(db_column='requested_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.admin')),
            ],
            options={
                'db_table': 'replacement_request',
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_number', models.CharField(max_length=50, unique=True)),
                ('requested_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('return_tracking', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('shipped', 'Shipped Back'), ('received_supplier', 'Received by Supplier'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rejected_item', models.ForeignKey(db_column='rejected_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.rejecteditem')),
                ('requested_by', models.ForeignKey(db_column='requested_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.admin')),
            ],
            options={
                'db_table': 'return_request',
            },
        ),
    ]
