# Generated by Django 5.1.7 on 2025-12-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_purchasereceiving_receiving_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition_item',
            name='issued_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='requisition_item',
            name='reserved_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
